---
gendate: "{{ ansible_date_time.iso8601 }}"
show_debug: false

mgmt_usr: lvsadmin
mgmt_grp: lvsadmin

#jenkins vars
jenkins_url: http://192.168.50.200:8080

#search folder
default_file_input: input
input_folder: "{{ default_file_input }}"


#location for storing output files
default_file_output: output
report_output_folder: "{{ default_file_output }}/reports/"
archive_folder: "{{ default_file_input }}/archive"
junk_folder: "{{ archive_folder }}/junk_folder" #files that don't match criteria
cron_folder: "{{ archive_folder }}/cron_folder" #files added to cron
failed_folder: "{{ archive_folder }}/failed_folder" #accts that failed
disabled_folder: "{{archive_folder }}/disabled_folder" #accts disabled
tmp_folder: "{{ default_file_output }}/tmp_folder" #accts disabled list temp
accts_folder: "{{ default_file_output }}/accts_folder" #temp accts found list temp
client_sh_folder: "{{ default_file_output }}/client_sh_folder"

#location paths for openvpn
openvpn_path: "/etc/openvpn"
openvpn_path_ccd: "{{ openvpn_path }}/ccd"
openvpn_ifconfig_pool_persist_file: "{{ openvpn_path }}/ipp.txt"
openvpn_key_dir: "{{ openvpn_path_keys }}"
openvpn_client_sh_dir: "{{ openvpn_path }}/client_sh"
openvpn_path_easyrsa: "{{ openvpn_path }}/easy-rsa"
openvpn_path_easyrsa_vars: "{{ openvpn_path_easyrsa }}/vars"
openvpn_path_pki: "{{ openvpn_path_easyrsa }}/pki"
openvpn_path_certs: "{{ openvpn_path_pki }}/issued"
openvpn_path_reqs: "{{ openvpn_path_pki }}/reqs"
openvpn_hmac_firewall: "{{ openvpn_path_pki }}/ta.key"
openvpn_ca_cert: "{{ openvpn_path_pki }}/ca.crt"
openvpn_path_keys: "{{ openvpn_path_pki }}/private"
dhparams_size: "{{ openvpn_key_size }}"
dhparams_location: "{{ openvpn_path_pki }}/dh.pem"
openvpn_crl: "{{ openvpn_path_pki }}/crl.pem"
openvpn_server_common_name_file: "{{ openvpn_path }}/openvpn_server_common_name"
openvpn_server: "tbd"
openvpn_proto: udp
openvpn_port: 1194





crl_days: 3650
delete_log: "/var/log/openvpn_delete.log"

class_c_ip: "{{ openvpn_class_c }}"
start_ip: "{{ class_c_ip }}.2"
end_ip: "{{ class_c_ip }}.253"
DELETE_LOG: "/var/log/openvpn/client_delete.log"
CONNECTION_LOG: /var/log/openvpn/client_config.log
ip_range_start: 2
ip_range_end: 253
openvpn_gateway: "{{ class_c_ip }}.1"
openvpn_subnet_mask: "255.255.255.0"

ansible_python_interpreter: /usr/bin/python3.11






depots_folder: /depots/builds/ansible/lvsadmin/ansible_nix_generic_ovpn/
#depots_folder: /home/lvsadmin/ansible/ansible_acct_management/ #this is used for creating cronjob

show_debug: false

lvs_acct_warning: 30
lvs_acct_disable: 60
lvs_acct_delete: 93

gendate: "{{ ansible_date_time.iso8601 }}"

BGColorGood: 4CBB17
BGColorWarn: FFFC33
BGColorCrit: ff4d4d
BGColorTbl: EAECEE
BGColorsec: ff0000
BGColorbug: 00b33c
BGColorenh: 867979
BGColorpatches: 0000ff


