---
loop_break: false

openvpn_server: "tbd" #not the vpn private address
openvpn_server_common_name: "Easy-RSA CA" #openvpn_server_common_name if one is not provide random gen name is created
ca_password: [] #if one is not provide random gen pwd is created
pem_password: []
svr_key_password: []
openvpn_key_size: "2048"
openvpn_cipher: "AES-128-GCM"
openvpn_auth_digest: "SHA256"
openvpn_auth_alg: "SHA512"
# For all available ciphers use: openvpn --show-tls
# For all available PFS ciphers (without eliptic curve cryptography) use: openvpn --show-tls | grep -e "-DHE-"
# Configuration here just uses PFS ciphers leveraging AES256 and at least SHA256
#openvpn_tls_cipher: "TLS-DHE-DSS-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256:TLS-DHE-DSS-WITH-AES-256-CBC-SHA256"
openvpn_tls_cipher: "TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256"
openvpn_proto: udp
openvpn_port: 1194