---
#include task files


- name: generic ovpn client management | main | Enable IPv4 traffic forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: generic ovpn client management | main | Gather OpenVPN client configurations
  ansible.builtin.find:
    paths: "{{ openvpn_path_ccd }}"
    recurse: no
    patterns: "*"
  register: ccd_files

- name: generic ovpn client management | main | Create a list of client data
  set_fact:
    client_data: []

# - name: generic ovpn client management | main | Loop over the list of files
#   include_tasks: extract_data.yml
#   loop: "{{ ccd_files.files }}"
#   loop_control:
#     loop_var: item


- name: generic ovpn client management | main | delete client
  ansible.builtin.include_tasks: "del_client.yml"


# - name: generic ovpn client management | main | run debug tasks if show_debug var true
#   ansible.builtin.include_tasks: "debug_vars.yml"

